# Generated by Django 4.2.7 on 2024-01-24 09:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, validators=[django.core.validators.EmailValidator])),
                ('subject', models.CharField(max_length=40)),
                ('body', models.TextField(max_length=500)),
            ],
        ),
    ]
